- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel
  tags:
    - aur_packages

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  tags:
    - aur_packages

- name: Install AUR packages
  kewlfft.aur.aur:
    use: yay
    name:
      - php74
      - slack-desktop
      - insomnia
      - espanso
      - ddev-bin
      - brave
  become: yes
  become_user: aur_builder
  tags:
    - aur_packages
