- name: Install packages (using pacman)
  pacman:
    name: tmux, ripgrep, fzf, bat, gimp, xclip, copyq, flameshot, firefox-developer-edition, nautilus, alacritty, gnome-calendar, gnome-calculator, file-roller, gparted, vlc, eog, libreoffice-still, evince, python-adblock, redshift
  tags:
    - install
    - productivity

- name: Install platform.sh cli
  become_user: nkoporec
  shell: curl -fsS https://platform.sh/cli/installer | php
  tags:
    - install
    - productivity
