- name: Create project folders
  become_user: nkoporec
  shell: mkdir /home/nkoporec/personal && mkdir /home/nkoporec/work && mkdir /home/nkoporec/work/opensocial
  tags:
    - install
    - projects

- name: Create platform.sh project folder
  become_user: nkoporec
  shell: mkdir /home/nkoporec/work/platformsh
  tags:
    - install
    - projects

- name: Clone social-ddev project
  become_user: nkoporec
  shell: cd {{ lookup('env', 'HOME') }}/work/opensocial && git clone git@github.com:nkoporec/social-ddev.git open-social
  tags:
    - install
    - projects

- name: Clone dump project
  become_user: nkoporec
  shell: cd {{ lookup('env', 'HOME') }}/personal && git clone git@github.com:nkoporec/dump.git dump
  tags:
    - install
    - projects
